services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    restart: always

  worker:
    build: .
    command: ["npm", "run", "worker"]
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    restart: always

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    env_file:
      - .env  # Use the .env file instead of explicitly defining environment variables here
    volumes:
      - redis-data:/data  # Persist Redis data

      

  postgres:
    image: "postgres:17-alpine"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env  # Use the .env file instead of explicitly defining environment variables here
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  redis-data:
